# Generated by Django 4.2.21 on 2025-05-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание профессии (2000+ символов)')),
                ('image', models.ImageField(upload_to='main/', verbose_name='Изображение профессии')),
            ],
        ),
        migrations.CreateModel(
            name='StatSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('overview', 'Общая статистика'), ('demand', 'Востребованность'), ('geo', 'География'), ('skills', 'Навыки')], max_length=20, verbose_name='Раздел')),
                ('name', models.CharField(max_length=255, verbose_name='Название блока (например, Динамика зарплат)')),
                ('html_table', models.TextField(verbose_name='HTML таблица')),
                ('image', models.ImageField(upload_to='graphs/', verbose_name='График')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('salary_from', models.FloatField(blank=True, null=True)),
                ('salary_to', models.FloatField(blank=True, null=True)),
                ('salary_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('area_name', models.CharField(blank=True, max_length=255, null=True)),
                ('published_at', models.DateField(blank=True, null=True)),
                ('key_skills', models.TextField(blank=True, null=True)),
                ('is_relevant', models.BooleanField(default=True)),
            ],
        ),
    ]

